name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - name: Run tests
      run: go test -race ./...

    - name: Run vet
      run: go vet ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - name: Build CLI application
      run: go build -o osz2-cli ./cmd/cli/

    - name: Upload CLI artifact
      uses: actions/upload-artifact@v7
      with:
        name: osz2-cli
        path: osz2-cli
